const axios = require('axios');

const FOOTER = '\n\n> Draxen is fast';
const PAIR_LINK = '\n> 🔗 Pair: https://dullahxmd-v2.vercel.app';

module.exports = {
    name: 'lyrics',
    async execute(socket, msg, number, userConfig, loadUserConfigFromMongo) {

        const fakeQuoted = {
            key: { participant: '0@s.whatsapp.net', remoteJid: '0@s.whatsapp.net', id: msg.key.id },
            message: { conversation: "Verified" },
            contextInfo: { mentionedJid: [], forwardingScore: 999, isForwarded: true }
        };
        const text = msg.message?.conversation || msg.message?.extendedTextMessage?.text || "";
        const args = text.trim().split(/\s+/);
        const query = args.slice(1).join(' ');

        if (!query) {
            return socket.sendMessage(msg.key.remoteJid, {
                text: "Are you mute? Give me a song title so I can find the lyrics you'll probably mispronounce anyway." + FOOTER + PAIR_LINK
            }, { quoted: fakeQuoted });
        }

        try {
            await socket.sendMessage(msg.key.remoteJid, { react: { text: '⌛', key: msg.key } });

            const { data } = await axios.get(`https://api.deline.web.id/tools/lyrics`, {
                params: { title: query }
            });

            if (!data.status || !data.result || data.result.length === 0) {
                await socket.sendMessage(msg.key.remoteJid, { react: { text: '❌', key: msg.key } });
                return socket.sendMessage(msg.key.remoteJid, {
                    text: `I couldn't find any lyrics for "${query}". Either the song is trash or your spelling is.` + FOOTER + PAIR_LINK
                }, { quoted: fakeQuoted });
            }

            const song = data.result[0];
            const sanitized = (number || '').replace(/[^0-9]/g, '');
            const cfg = await loadUserConfigFromMongo(sanitized) || {};
            const botName = cfg.botName || 'DRAXEN-Ai';

            const lyricText = `*『 𝙻𝚈𝚁𝙸𝙲𝚂 𝙵𝙸𝙽𝙳𝙴𝚁 』*

╭───(    \`𝚂𝚘𝚗𝚐 𝙳𝚎𝚝𝚊𝚒𝚕𝚜\`    )───
> ───≫ 🎵 𝚃𝚒𝚝𝚕𝚎 : ${song.name}
> ───≫ 👤 𝙰𝚛𝚝𝚒𝚜𝚝 : ${song.artistName}
> ───≫ 💿 𝙰𝚕𝚋𝚞𝚖 : ${song.albumName || 'N/A'}
╰──────────────────☉

${song.plainLyrics}

*Generated by ${botName}*`;

            await socket.sendMessage(msg.key.remoteJid, { react: { text: '✅', key: msg.key } });

            await socket.sendMessage(msg.key.remoteJid, {
                text: lyricText + FOOTER + PAIR_LINK
            }, { quoted: fakeQuoted });

        } catch (error) {
            await socket.sendMessage(msg.key.remoteJid, { react: { text: '❌', key: msg.key } });
            await socket.sendMessage(msg.key.remoteJid, {
                text: "Lyrics search crashed harder than your singing career. Try again later." + FOOTER + PAIR_LINK
            }, { quoted: fakeQuoted });
        }
    }
};
